# -*- coding: utf-8 -*-
"""1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NUvlKXKHGpcYkvw4Hq44L9gAzpQTwHjl
"""

#  1) Write a python program to implement and plot the given below Activation
# Functions of neural networks.
# a) Linear
# b) Sigmoid
# c) Tanh
# d) ReLU
# e) Softmax

  import numpy as np
  import matplotlib.pyplot as plt

  # Input values
  x = np.linspace(-10, 10, 100)

  # a) Linear Activation Function
  linear = x

  # b) Sigmoid Activation Function
  sigmoid = 1 / (1 + np.exp(-x))

  # c) Tanh Activation Function
  tanh = np.tanh(x)

  # d) ReLU Activation Function
  relu = np.maximum(0, x)

  # e) Softmax Activation Function
  softmax = np.exp(x) / np.sum(np.exp(x))

  # Plot all activation functions
  plt.figure(figsize=(12, 8))

  plt.subplot(3, 2, 1)
  plt.plot(x, linear)
  plt.title("Linear Activation Function")
  plt.grid()

  plt.subplot(3, 2, 2)
  plt.plot(x, sigmoid)
  plt.title("Sigmoid Activation Function")
  plt.grid()

  plt.subplot(3, 2, 3)
  plt.plot(x, tanh)
  plt.title("Tanh Activation Function")
  plt.grid()

  plt.subplot(3, 2, 4)
  plt.plot(x, relu)
  plt.title("ReLU Activation Function")
  plt.grid()

  plt.subplot(3, 2, 5)
  plt.plot(x, softmax)
  plt.title("Softmax Activation Function")
  plt.grid()

  plt.tight_layout()
  plt.show()

# 2) Implement a Single layer perceptron using a tensorflow library and calculate
# the accuracy of the model on the testing data. (Use MNIST dataset)

import tensorflow as tf
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Dense
from tensorflow.keras.datasets import mnist
from sklearn.metrics import accuracy_score

# Load MNIST dataset
(x_train, y_train), (x_test, y_test) = mnist.load_data()

# Normalize the data
x_train = x_train / 255.0
x_test = x_test / 255.0

# Create Single Layer Perceptron model
model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(10, activation='softmax')
])

# Compile the model
model.compile(
    optimizer='sgd',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# Train the model
model.fit(x_train, y_train, epochs=5)

# Evaluate the model on testing data
loss, accuracy = model.evaluate(x_test, y_test)

print("Test Accuracy:", accuracy * 100, "%")

# 3) Write a python program to implement     OR gate      using a single layer
# perceptron learning rule.

import numpy as np

# OR Gate Input and Output
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])

y = np.array([0, 1, 1, 1])

# Initialize weights and bias
weights = np.zeros(2)
bias = 0
learning_rate = 0.1
epochs = 10

# Perceptron Learning Rule
for epoch in range(epochs):
    for i in range(len(X)):
        net = np.dot(X[i], weights) + bias

        # Step Activation Function
        output = 1 if net > 0 else 0

        # Calculate error
        error = y[i] - output

        # Update weights and bias
        weights = weights + learning_rate * error * X[i]
        bias = bias + learning_rate * error

# Display Output
print("OR Gate Output:")
for i in range(len(X)):
    net = np.dot(X[i], weights) + bias
    output = 1 if net > 0 else 0
    print(X[i], "=", output)

# 4) Write a python program to implement       AND gate      using a single layer
# perceptron learning rule.
import numpy as np

# AND Gate Input and Output
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])

y = np.array([0, 0, 0, 1])

# Initialize weights and bias
weights = np.zeros(2)
bias = 0
learning_rate = 0.1
epochs = 10

# Perceptron Learning Rule
for epoch in range(epochs):
    for i in range(len(X)):
        net = np.dot(X[i], weights) + bias

        # Step Activation Function
        output = 1 if net > 0 else 0

        # Calculate Error
        error = y[i] - output

        # Update Weights and Bias
        weights = weights + learning_rate * error * X[i]
        bias = bias + learning_rate * error

# Display Output
print("AND Gate Output:")
for i in range(len(X)):
    net = np.dot(X[i], weights) + bias
    output = 1 if net > 0 else 0
    print(X[i], "=", output)

# 1) Write a python program to implement and plot the given below Activation
# Functions of neural networks.
# a) Hard Tanh
# b) Leaky ReLU
# c) ELU
# Parametric ReLU (PReLU)  Extra

import numpy as np
import matplotlib.pyplot as plt

# Input values
x = np.linspace(-5, 5, 200)

# Hard Tanh
def hard_tanh(x):
    return np.clip(x, -1, 1)

# Leaky ReLU
def leaky_relu(x, alpha=0.01):
    return np.where(x > 0, x, alpha * x)

# Parametric ReLU (PReLU)
def parametric_relu(x, alpha=0.25):
    return np.where(x > 0, x, alpha * x)

# ELU
def elu(x, alpha=1):
    return np.where(x >= 0, x, alpha * (np.exp(x) - 1))

# Plotting
plt.figure(figsize=(10, 8))

plt.subplot(2,2,1)
plt.plot(x, hard_tanh(x))
plt.title("Hard Tanh")
plt.grid(True)

plt.subplot(2,2,2)
plt.plot(x, leaky_relu(x))
plt.title("Leaky ReLU")
plt.grid(True)

plt.subplot(2,2,3)
plt.plot(x, parametric_relu(x))
plt.title("Parametric ReLU")
plt.grid(True)

plt.subplot(2,2,4)
plt.plot(x, elu(x))
plt.title("ELU")
plt.grid(True)

plt.tight_layout()
plt.show()

# 2) Write a python program to implement a        NAND gate          using a single layer
# perceptron learning rule.

import numpy as np

# Input
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

# Target Output (NAND Gate)
Y = np.array([1, 1, 1, 0])

# Initialize
weights = np.zeros(2)
bias = 0
learning_rate = 0.1
epochs = 10

print("WEIGHT UPDATION STEPS")

for epoch in range(epochs):
    for i in range(len(X)):
        x = X[i]
        target = Y[i]

        # Net Input
        net = np.dot(x, weights) + bias

        # Activation Function
        output = 1 if net >= 0 else 0

        # Error
        error = target - output

        old_weights = weights.copy()

        # Update Weights & Bias
        weights = weights + learning_rate * error * x
        bias = bias + learning_rate * error

        # Print only if weights changed
        if not np.array_equal(old_weights, weights):
            print("\n----------------------------")
            print("Input        :", x)
            print("Target       :", target)
            print("Old Weights  :", old_weights)
            print("New Weights  :", weights)

print("\n----------------------------")
print("Final Weights :", weights)
print("Final Bias    :", bias)

print("\nNAND Gate Output")
for x in X:
    net = np.dot(x, weights) + bias
    output = 1 if net >= 0 else 0
    print(x, "->", output)