# -*- coding: utf-8 -*-
"""2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hxcUTwE9eabjy43dRelBTuI3OQCl2FZU
"""

# 1) Write a python program to implement XOR gate using a multi layer
# perceptron learning rule.

import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Input
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

# Expected Output
Y = np.array([[0], [1], [1], [0]])

# Create MLP Model
model = Sequential()

# Hidden Layer
model.add(Dense(4, input_dim=2, activation='sigmoid'))

# Output Layer
model.add(Dense(1, activation='sigmoid'))

# Compile Model
model.compile(
    optimizer='adam',
    loss='mean_squared_error',
    metrics=['accuracy']
)

# Train Model
model.fit(X, Y, epochs=5000, verbose=0)

# Test Model
predictions = model.predict(X, verbose=0)

# Display Output
for i in range(len(X)):
    output = 1 if predictions[i][0] >= 0.5 else 0
    print(X[i][0], "XOR", X[i][1], "=", output)

# 2) Implement a Multi layer perceptron using a tensorflow library and calculate
# the accuracy of the model on the testing data. (Use MNIST dataset).

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten

# Load MNIST Dataset
(X_train, Y_train), (X_test, Y_test) = tf.keras.datasets.mnist.load_data()

# Normalize Data
X_train = X_train / 255.0
X_test = X_test / 255.0

# Create MLP Model
model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

# Compile Model
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# Train Model
model.fit(X_train, Y_train, epochs=5, batch_size=32)

# Evaluate Model on Testing Data
loss, accuracy = model.evaluate(X_test, Y_test)

# Display Accuracy
print("Testing Accuracy:", accuracy * 100, "%")

# 3) Write a python program to implement handwritten digit classification using
#     ANN. (Use MNIST dataset)

#Ass2SetA3

import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten

# Load MNIST dataset
(X_train, y_train), (X_test, y_test) = tf.keras.datasets.mnist.load_data()

# Normalize pixel values
X_train = X_train / 255.0
X_test = X_test / 255.0

# Create ANN model
model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(128, activation='relu'),
    Dense(64, activation='relu'),
    Dense(10, activation='softmax')
])

# Compile the model
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# Display model architecture
model.summary()

# Train the model
history = model.fit(
    X_train,
    y_train,
    epochs=10,
    batch_size=32,
    validation_split=0.1
)

# Evaluate model on test data
test_loss, test_accuracy = model.evaluate(X_test, y_test)

print("\nTest Accuracy:", test_accuracy)
print("Test Accuracy (%):", test_accuracy * 100)

# Predict test images
predictions = model.predict(X_test)

# Display first 10 predictions
plt.figure(figsize=(10, 5))

for i in range(10):
    plt.subplot(2, 5, i + 1)

    plt.imshow(X_test[i], cmap='gray')

    predicted_digit = predictions[i].argmax()

    plt.title(
        f"Actual: {y_test[i]}\nPredicted: {predicted_digit}"
    )

    plt.axis('off')

plt.tight_layout()
plt.show()

# Plot training accuracy
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')

plt.title("ANN Training Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend()
plt.show()

# 4) Write a python program to implement Regression Analysis using ANN. (Use
# california_housing_train.csv)

import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Load Dataset
url = "https://download.mlcc.google.com/mledu-datasets/california_housing_train.csv"
data = pd.read_csv(url)

print("Dataset Loaded Successfully")
print(data.head())

# Separate Input and Output
X = data.drop("median_house_value", axis=1)
Y = data["median_house_value"]

# Split Dataset
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2, random_state=42
)

# Scale Input Data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Create ANN Model
model = Sequential([
    Dense(64, activation="relu", input_shape=(X_train.shape[1],)),
    Dense(32, activation="relu"),
    Dense(1)
])

# Compile Model
model.compile(
    optimizer="adam",
    loss="mse",
    metrics=["mae"]
)

# Train Model
model.fit(
    X_train, Y_train,
    epochs=20,
    batch_size=32,
    verbose=1
)

# Evaluate Model
loss, mae = model.evaluate(X_test, Y_test)

print("Test Loss:", loss)
print("Mean Absolute Error:", mae)

# Predict House Prices
predictions = model.predict(X_test[:5])

print("Actual House Prices:", Y_test.iloc[:5].values)
print("Predicted House Prices:", predictions.flatten())

# 5) Write a python program to build a Feed forward Neural network using
# Sigmoid activation function. (Use MNIST dataset)


import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten

# Load MNIST Dataset
(X_train, Y_train), (X_test, Y_test) = tf.keras.datasets.mnist.load_data()

# Normalize Data
X_train = X_train / 255.0
X_test = X_test / 255.0

# Build Feed Forward Neural Network
model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(128, activation='sigmoid'),
    Dense(10, activation='softmax')
])

# Compile Model
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

# Train Model
model.fit(X_train, Y_train, epochs=5, batch_size=32)

# Evaluate Model
loss, accuracy = model.evaluate(X_test, Y_test)

# Display Accuracy
print("Test Accuracy:", accuracy * 100, "%")

# 1) Write a python program to implement XNOR gate using a multi layer
# perceptron learning rule.

import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Input
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

# Target Output
Y = np.array([1, 0, 0, 1])

# Create MLP Model
model = Sequential([
    Dense(4, input_dim=2, activation='sigmoid'),
    Dense(1, activation='sigmoid')
])

# Compile Model
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# Train Model
model.fit(X, Y, epochs=5000, verbose=0)

# Predict Output
predictions = model.predict(X, verbose=0)

# Display Results
for i in range(len(X)):
    output = 1 if predictions[i][0] >= 0.5 else 0
    print(X[i][0], "XNOR", X[i][1], "=", output)

# 2) Write a python program to implement Feedforward neural network using
# Tanh activation function.

import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Input Data
X = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

# Target Output (XOR)
Y = np.array([0, 1, 1, 0])

# Create Feedforward Neural Network
model = Sequential([
    Dense(4, input_dim=2, activation='tanh'),
    Dense(1, activation='sigmoid')
])

# Compile Model
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# Train Model
model.fit(X, Y, epochs=1000, verbose=0)

# Predict Output
predictions = model.predict(X, verbose=0)

# Display Results
for i in range(len(X)):
    output = 1 if predictions[i][0] >= 0.5 else 0
    print(X[i][0], "XOR", X[i][1], "=", output)