# -*- coding: utf-8 -*-
"""Copy of 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YOFiPlF7CuS3AotYq1Uxhq0b2YBGY7d1
"""

# 1) Create a simple RNN model for generating data using text and predict the
# text using a pre-trained model.(Use ReLU and Softmax activation function).
# (Use shakespeare.txt file)

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense, Embedding

# Load the dataset
with open("shakespeare.txt", "r", encoding="utf-8") as file:
    text = file.read().lower()

# Use a small portion of the text
text = text[:20000]

# Create character vocabulary
chars = sorted(set(text))
char_to_num = {c: i for i, c in enumerate(chars)}
num_to_char = {i: c for i, c in enumerate(chars)}

# Convert characters into numbers
data = np.array([char_to_num[c] for c in text])

# Prepare input and output sequences
seq_length = 40
X = []
y = []

for i in range(len(data) - seq_length):
    X.append(data[i:i + seq_length])
    y.append(data[i + seq_length])

X = np.array(X)
y = np.array(y)

# Create the RNN model
model = Sequential([
    Embedding(len(chars), 32),
    SimpleRNN(64, activation="relu"),
    Dense(len(chars), activation="softmax")
])

# Compile the model
model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

# Display model summary
model.summary()

# Train the model
model.fit(X, y, epochs=5, batch_size=64)

# Generate text
seed = text[:40]
generated_text = seed

for i in range(200):
    input_seq = np.array(
        [[char_to_num[c] for c in generated_text[-seq_length:]]]
    )

    prediction = model.predict(input_seq, verbose=0)
    next_char = num_to_char[np.argmax(prediction)]

    generated_text += next_char

print("\nGenerated Text:\n")
print(generated_text)

# 2) Write a python program to implement time series forecasting in Recurrent
# Neural network using LSTM module.( Use monthly_milk_production.csv)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

# Load dataset using URL
url = "https://raw.githubusercontent.com/plotly/datasets/master/monthly-milk-production-pounds.csv"
data = pd.read_csv(url)

# Select milk production column
milk = data.iloc[:, 1].values.reshape(-1, 1)

# Normalize data
scaler = MinMaxScaler()
milk = scaler.fit_transform(milk)

# Prepare data
X = []
y = []

for i in range(12, len(milk)):
    X.append(milk[i-12:i, 0])
    y.append(milk[i, 0])

X = np.array(X)
y = np.array(y)

X = X.reshape(X.shape[0], X.shape[1], 1)

# Create LSTM model
model = Sequential([
    LSTM(50, activation="tanh", input_shape=(12, 1)),
    Dense(1)
])

# Compile model
model.compile(optimizer="adam", loss="mean_squared_error")

# Train model
model.fit(X, y, epochs=20, batch_size=16)

# Predict next month
last_12 = milk[-12:].reshape(1, 12, 1)
prediction = model.predict(last_12, verbose=0)
prediction = scaler.inverse_transform(prediction)

print("Predicted Milk Production:", prediction[0][0])

# Plot graph
plt.plot(scaler.inverse_transform(milk), label="Actual Milk Production")
plt.title("Milk Production Forecasting using LSTM")
plt.xlabel("Months")
plt.ylabel("Milk Production (pounds per cow)")
plt.legend()
plt.show()

# 3) Write a python program to predict a stock price from a mastercard stock
# dataset using LSTM and GRU models.


# Assignment 4 - Set A - Q3
# Stock Price Prediction using LSTM and GRU

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, GRU, Dense

# Load dataset from URL
url = "https://raw.githubusercontent.com/andresca94/MasterCard-Stock-Price-Prediction-Using-LSTM-and-GRU/main/Mastercard_stock_history.csv"
data = pd.read_csv(url)

# Select closing price
prices = data["Close"].values.reshape(-1, 1)

# Normalize data
scaler = MinMaxScaler()
prices = scaler.fit_transform(prices)

# Prepare sequences
X, y = [], []
for i in range(60, len(prices)):
    X.append(prices[i-60:i, 0])
    y.append(prices[i, 0])

X = np.array(X)
y = np.array(y)
X = X.reshape(X.shape[0], X.shape[1], 1)

# Split into training and testing data
split = int(len(X) * 0.8)
X_train, X_test = X[:split], X[split:]
y_train, y_test = y[:split], y[split:]

# Create LSTM model
lstm_model = Sequential([
    LSTM(50, input_shape=(60, 1)),
    Dense(1)
])

lstm_model.compile(optimizer="adam", loss="mean_squared_error")
lstm_model.fit(X_train, y_train, epochs=5, batch_size=32, verbose=1)

# Create GRU model
gru_model = Sequential([
    GRU(50, input_shape=(60, 1)),
    Dense(1)
])

gru_model.compile(optimizer="adam", loss="mean_squared_error")
gru_model.fit(X_train, y_train, epochs=5, batch_size=32, verbose=1)

# Predict stock prices
lstm_pred = lstm_model.predict(X_test, verbose=0)
gru_pred = gru_model.predict(X_test, verbose=0)

# Convert predictions to original prices
lstm_pred = scaler.inverse_transform(lstm_pred)
gru_pred = scaler.inverse_transform(gru_pred)
actual = scaler.inverse_transform(y_test.reshape(-1, 1))

# Calculate RMSE
print("LSTM RMSE:", np.sqrt(mean_squared_error(actual, lstm_pred)))
print("GRU RMSE:", np.sqrt(mean_squared_error(actual, gru_pred)))

# Plot results
plt.figure(figsize=(10, 5))
plt.plot(actual, label="Actual Price")
plt.plot(lstm_pred, label="LSTM Prediction")
plt.plot(gru_pred, label="GRU Prediction")
plt.title("Mastercard Stock Price Prediction")
plt.xlabel("Days")
plt.ylabel("Stock Price")
plt.legend()
plt.show()

# 4) Write a python program to create a sequential model that processes
# sequences of integers, embeds each integer into a 64-dimensional vector, and
# then process the sequence of vectors using a LSTM layer.

# Assignment 4 - Set A - Q4
# Sequential Model using Embedding and LSTM

import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM

# Input sequences of integers
X = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15]
])

# Create Sequential Model
model = Sequential([
    Embedding(input_dim=100, output_dim=64, input_length=5),
    LSTM(32)
])

# Display model summary
model.summary()

# Process input sequences
output = model.predict(X)

print("\nOutput Shape:", output.shape)
print("\nOutput:")
print(output)

# 1) Create a Bi-directional RNN model to perform sentiment analysis and
# predict the sentiment for a given user sentence and also compute the model
# accuracy and model loss with respect to the number of epochs.

# Assignment 5 - Q1
# Bi-directional RNN for Sentiment Analysis

import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.datasets import imdb
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Bidirectional, LSTM, Dense
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Load dataset
vocab_size = 10000
max_length = 200

(X_train, y_train), (X_test, y_test) = imdb.load_data(num_words=vocab_size)

# Pad sequences
X_train = pad_sequences(X_train, maxlen=max_length)
X_test = pad_sequences(X_test, maxlen=max_length)

# Create model
model = Sequential([
    Embedding(vocab_size, 64),
    Bidirectional(LSTM(32)),
    Dense(1, activation="sigmoid")
])

# Compile model
model.compile(optimizer="adam",
              loss="binary_crossentropy",
              metrics=["accuracy"])

# Train model
history = model.fit(
    X_train, y_train,
    epochs=5,
    batch_size=64,
    validation_data=(X_test, y_test)
)

# Evaluate model
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print("Test Accuracy:", accuracy)
print("Test Loss:", loss)

# Plot accuracy
plt.plot(history.history["accuracy"], label="Training Accuracy")
plt.plot(history.history["val_accuracy"], label="Validation Accuracy")
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.title("Model Accuracy")
plt.legend()
plt.show()

# Plot loss
plt.plot(history.history["loss"], label="Training Loss")
plt.plot(history.history["val_loss"], label="Validation Loss")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.title("Model Loss")
plt.legend()
plt.show()

# Predict sentiment for user sentence
word_index = imdb.get_word_index()

def predict_sentiment(sentence):
    sequence = [1]
    for word in sentence.lower().split():
        index = word_index.get(word, 2) + 3
        sequence.append(index if index < vocab_size else 2)

    sequence = pad_sequences([sequence], maxlen=max_length)
    prediction = model.predict(sequence, verbose=0)[0][0]

    if prediction >= 0.5:
        print("Sentiment: Positive")
    else:
        print("Sentiment: Negative")

# Test sentence
predict_sentiment("This movie is very good and wonderful")

# 2) Write a python program to recognize handwritten digits using RNN.

# Assignment 5 - Q2
# Handwritten Digit Recognition using RNN

import matplotlib.pyplot as plt
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense

# Load MNIST dataset
(X_train, y_train), (X_test, y_test) = mnist.load_data()

# Normalize data
X_train = X_train / 255.0
X_test = X_test / 255.0

# Create RNN model
model = Sequential([
    SimpleRNN(128, activation="tanh", input_shape=(28, 28)),
    Dense(10, activation="softmax")
])

# Compile model
model.compile(optimizer="adam",
              loss="sparse_categorical_crossentropy",
              metrics=["accuracy"])

# Train model
model.fit(X_train, y_train, epochs=5, batch_size=64)

# Evaluate model
loss, accuracy = model.evaluate(X_test, y_test)
print("Test Accuracy:", accuracy)
print("Test Loss:", loss)

# Predict digit
prediction = model.predict(X_test[:1])
digit = prediction.argmax()

print("Predicted Digit:", digit)
print("Actual Digit:", y_test[0])

# Display handwritten digit
plt.imshow(X_test[0], cmap="gray")
plt.title("Predicted Digit: " + str(digit))
plt.axis("off")
plt.show()